### ISSUE TITLE
freebase

### ISSUE THREAD

**Issue by briatte** [yonicd/noplyr#1]
This package and the [freebase](https://github.com/hrbrmstr/freebase) package by @hrbrmstr seem to share a common logic. Mention it in the README, perhaps?

**Comment by yonicd** [comment]
Thank you for pointing that out. 

I am a contributor to freebase tidyr functions, but they differ in concept a bit. 

freebase is only base r and is built via a use_* api. 

noplyr is base r + rlang and has direct calls to functions . 

We can discuss if they may be combined.

**Comment by yonicd** [comment]
readme updated linking to freebase

**Comment by hrbrmstr** [comment]
I just added a note/link to here in freebase's readme as well.

**Comment by yonicd** [comment]
thanks!
